// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7v6ESTXloyU8t-s8Ar9WmIEY8xN0zbs',
    appId: '1:447639335038:web:9d7633530b0a1851e8a82f',
    messagingSenderId: '447639335038',
    projectId: 'paw-39cad',
    authDomain: 'paw-39cad.firebaseapp.com',
    storageBucket: 'paw-39cad.appspot.com',
    measurementId: 'G-B45LZBNW8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaoGqGS_UDsVbbqsNWEcIrPa_K6BenpLk',
    appId: '1:447639335038:android:ea72d4b332098d5be8a82f',
    messagingSenderId: '447639335038',
    projectId: 'paw-39cad',
    storageBucket: 'paw-39cad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgA4Bmosj1_QJ5wevASslsfaNisgHjUOk',
    appId: '1:447639335038:ios:d1e6a755f8107484e8a82f',
    messagingSenderId: '447639335038',
    projectId: 'paw-39cad',
    storageBucket: 'paw-39cad.appspot.com',
    iosClientId: '447639335038-oc2jcr56snf4vml18rimafr8m8qh5593.apps.googleusercontent.com',
    iosBundleId: 'com.example.namTraining',
  );
}
